version: 2

sources:
  - name: jaffle_shop
    database: raw  
    schema: jaffle_shop  
    tables:
      - name: orders
      - name: customers
      - name: products

  - name: snowflake
    database: snowflake_sample_data
    schema: TPCDS_SF100TCL
    tables:
      - name: customer